# Generated by Django 5.0.6 on 2024-07-14 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('aud_id', models.AutoField(primary_key=True, serialize=False)),
                ('aud_file', models.FileField(upload_to='Audio/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_file', models.FileField(upload_to='Image/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('vid_id', models.AutoField(primary_key=True, serialize=False)),
                ('vid_file', models.FileField(max_length=10000000000, upload_to='Video/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
